### ISSUE TITLE
全新安装管理页面进不去

### ISSUE THREAD

**Issue by cn0068** [songwonderful/blog-website#10]
![屏幕截图 2021-08-28 103448](https://user-images.githubusercontent.com/62278175/131203596-d56a50d5-a698-465e-90d5-4a896e6c2695.png)
用的最新版本，请问是什么原因？

**Comment by songquanpeng** [comment]
运行 npm run build，因为后台管理界面需要 build

**Comment by cn0068** [comment]
宝塔里面如何运行啊？

**Comment by cn0068** [comment]
进ssh，按说明进行，中间出错。
启动项目，日志如下：
2021-08-28T13:31:14: Error: Please install sqlite3 package manually
2021-08-28T13:31:14:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:14:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:14:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:14:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:14:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:14:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:14:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:14:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:14:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:14:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:14: Error: Please install sqlite3 package manually
2021-08-28T13:31:14:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:14:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:14:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:14:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:14:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:14:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:14:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:14:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:14:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:14:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:15: Error: Please install sqlite3 package manually
2021-08-28T13:31:15:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:15:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:15:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:15:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:15:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:15:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:15:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:15:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:15:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:15:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:15: Error: Please install sqlite3 package manually
2021-08-28T13:31:15:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:15:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:15:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:15:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:15:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:15:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:15:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:15:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:15:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:15:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:15: Error: Please install sqlite3 package manually
2021-08-28T13:31:15:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:15:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:15:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:15:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:15:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:15:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:15:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:15:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:15:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:15:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:16: Error: Please install sqlite3 package manually
2021-08-28T13:31:16:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:16:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:16:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:16:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:16:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:16:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:16:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:16:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:16:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:16:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:16: Error: Please install sqlite3 package manually
2021-08-28T13:31:16:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:16:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:16:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:16:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:16:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:16:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:16:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:16:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:16:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:16:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:16: Error: Please install sqlite3 package manually
2021-08-28T13:31:16:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:16:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:16:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:16:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:16:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:16:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:16:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:16:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:16:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:16:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:16: Error: Please install sqlite3 package manually
2021-08-28T13:31:16:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:16:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:16:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:16:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:16:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:16:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:16:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:16:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:16:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:16:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:17: Error: Please install sqlite3 package manually
2021-08-28T13:31:17:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:17:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:17:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:17:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:17:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:17:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:17:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:17:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:17:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:17: Error: Please install sqlite3 package manually
2021-08-28T13:31:17:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:17:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:17:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:17:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:17:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:17:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:17:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:17:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:17:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:17: Error: Please install sqlite3 package manually
2021-08-28T13:31:17:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:17:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:17:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:17:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:17:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:17:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:17:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:17:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:17:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:18: Error: Please install sqlite3 package manually
2021-08-28T13:31:18:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:18:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:18:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:18:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:18:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:18:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:18:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:18:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:18:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:18:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:18: Error: Please install sqlite3 package manually
2021-08-28T13:31:18:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:18:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:18:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:18:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:18:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:18:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:18:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:18:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:18:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:18:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:18: Error: Please install sqlite3 package manually
2021-08-28T13:31:18:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:18:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:18:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:18:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:18:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:18:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:18:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:18:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:18:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:18:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-28T13:31:19: Error: Please install sqlite3 package manually
2021-08-28T13:31:19:     at ConnectionManager._loadDialectModule (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
2021-08-28T13:31:19:     at new ConnectionManager (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
2021-08-28T13:31:19:     at new SqliteDialect (/www/wwwroot/blog/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
2021-08-28T13:31:19:     at new Sequelize (/www/wwwroot/blog/node_modules/sequelize/lib/sequelize.js:340:20)
2021-08-28T13:31:19:     at Object.<anonymous> (/www/wwwroot/blog/common/database.js:4:19)
2021-08-28T13:31:19:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-28T13:31:19:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-28T13:31:19:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-28T13:31:19:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-28T13:31:19:     at Module.require (internal/modules/cjs/loader.js:961:19)

**Comment by songquanpeng** [comment]
https://github.com/sequelize/sequelize/issues/11174#issuecomment-509971784

试一下这个，很奇怪我本地安装没问题

**Comment by cn0068** [comment]
出错如下：请帮看一下

root@cn0068-exsi:/www/wwwroot# cd blog
root@cn0068-exsi:/www/wwwroot/blog# npm i sqlite3 -D && rm -rf node_modules && npm i && npm rebuild
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> sqlite3@4.1.1 install /www/wwwroot/blog/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v83-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.1.1 and node@14.17.5 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
make: 进入目录“/www/wwwroot/blog/node_modules/sqlite3/build”
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c
/bin/sh: python：未找到命令
make: *** [deps/action_before_build.target.mk:13：Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c] 错误 127
make: 离开目录“/www/wwwroot/blog/node_modules/sqlite3/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.11.0-27-generic
gyp ERR! command "/www/server/nvm/versions/node/v14.17.5/bin/node" "/www/server/nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/www/wwwroot/blog/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/www/wwwroot/blog/node_modules/sqlite3/lib/binding/node-v83-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /www/wwwroot/blog/node_modules/sqlite3
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/www/server/nvm/versions/node/v14.17.5/bin/node /www/server/nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/www/wwwroot/blog/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/www/wwwroot/blog/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/www/wwwroot/blog/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.11.0-27-generic
node-pre-gyp ERR! command "/www/server/nvm/versions/node/v14.17.5/bin/node" "/www/wwwroot/blog/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /www/wwwroot/blog/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.17.5
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/www/server/nvm/versions/node/v14.17.5/bin/node /www/server/nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/www/wwwroot/blog/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/www/wwwroot/blog/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-28T07_45_08_518Z-debug.log
root@cn0068-exsi:/www/wwwroot/blog#

**Comment by cn0068** [comment]
未运行以下这几行的时候，只是管理后台进不去，前台可以打开。现在前台也打不开了。
npm install
# 编译后台管理系统
npm run build  # Windows 用户请运行 `npm run build2`
# 启动服务
npm start

**Comment by songquanpeng** [comment]
看样子是安装 SQLite3 依赖时需要编译，需要用到 Python，但是你的环境里没有 Python：`/bin/sh: python：未找到命令`。

这个很奇怪哈，不用 root 账户试一下？

**Comment by songquanpeng** [comment]
> 未运行以下这几行的时候，只是管理后台进不去，前台可以打开。现在前台也打不开了。
> npm install
> 
> # 编译后台管理系统
> npm run build # Windows 用户请运行 `npm run build2`
> 
> # 启动服务
> npm start

`npm run build` 应该不会影响到前台的，这个命令的作用如下：进入 admin 目录，安装后台的依赖并编译打包，之后把文件复制到合适的位置。

我建议你重新安装一下，不要用 root 用户，因为我没有用 root 用户试过。

**Comment by cn0068** [comment]
root用户全局安装与普通用户权限搞乱了，所以出错。
sudo chown -R user /folder/

**Comment by songquanpeng** [comment]
现在搞定了吗？

**Comment by cn0068** [comment]
npm start运行半小时还未结束？
但网页前台，后台都可进了。
如何设置成中文？

**Comment by songquanpeng** [comment]
npm start 就是不会停的，这个就是启动服务器。

中文的话，前台你换个主题，后台的话暂时换不了。

**Comment by cn0068** [comment]
links , about在哪设置？
Error!:
No page has link "links".

**Comment by songquanpeng** [comment]
你新建文章，链接填 about 就好

**Comment by cn0068** [comment]
谢谢你的指导，差不多能运行了。明天再研究一下。有问题再请教！

**Comment by cn0068** [comment]
请问master与admin分支有什么不同？
安装了master,如何切换到admin?还需要重新安装吗？

**Comment by songquanpeng** [comment]
这个分支废弃了，忘记干嘛的了

**Comment by cn0068** [comment]
整合进自己的博客系统，每当有人登录时发微信消息提醒。这个如何整合？我看例子上是说的admin分支中的，mater分支中找不到

**Comment by songquanpeng** [comment]
![image](https://user-images.githubusercontent.com/39998050/131254650-a06efeda-2eed-4d58-9741-778a3692364f.png)

![image](https://user-images.githubusercontent.com/39998050/131254646-adb4eb50-7532-4842-8226-623e0f46a29a.png)

里面填：`https://domain/prefix/` 试一下

**Comment by songquanpeng** [comment]
如果不行的话重启试一下，应该是可以用的，但我不能确定

**Comment by cn0068** [comment]
好的，我试一下
